"""
Execution Engine — Phase 4 module.

Takes ranked decisions (`_decisions`) and produces concrete content
artifacts (markdown files) ready for human review.

Output per decision:
  - GitHub issue markdown (for build_feature decisions)
  - Email outreach draft (for reach_out decisions)
  - Campaign brief + ad copy variants (for launch_campaign)
  - Blog post outline + SEO keywords (for write_content)
  - Watchlist entry (for monitor_competitor)
  - Investigation ticket (for investigate)

All artifacts are written to `actions/<YYYY-MM-DD>/<decision_id>_<type>.md`
and listed in `items[0].metadata["_executions"]`.

This is GENERATION, not sending. The user reviews each artifact and
publishes/sends manually. This keeps the system safe and auditable
while still closing the loop Decide → Act.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from core.models import ProcessedItem
from core.logger import get_logger
from processors.base import BaseProcessor


class ExecutionEngine(BaseProcessor):
    name = "execution_engine"

    def __init__(self, config: dict | None = None):
        super().__init__(config)
        self._output_dir = Path(self._config.get("output_path", "actions"))
        self._max_artifacts = int(self._config.get("max_artifacts_per_run", 20))

    def _process(self, items: list[ProcessedItem]) -> list[ProcessedItem]:
        if not items:
            return items

        decisions_data = None
        for item in items:
            if "_decisions" in item.metadata:
                decisions_data = item.metadata["_decisions"]
                break

        if not decisions_data:
            self._logger.info("No decisions to execute — skipping execution engine")
            return items

        decisions = decisions_data.get("decisions", [])[: self._max_artifacts]

        artifacts: list[dict] = []
        for decision in decisions:
            try:
                artifact = self._execute_decision(decision)
                if artifact:
                    artifacts.append(artifact)
            except Exception as e:
                self._logger.error(f"Failed to execute decision {decision.get('id')}: {e}")

        # Write artifacts to disk
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        day_dir = self._output_dir / date_str
        day_dir.mkdir(parents=True, exist_ok=True)

        written: list[dict] = []
        for artifact in artifacts:
            filename = f"{artifact['decision_id']}_{artifact['type']}.md"
            filepath = day_dir / filename
            try:
                filepath.write_text(artifact["content"], encoding="utf-8")
                artifact["path"] = str(filepath)
                written.append(artifact)
            except Exception as e:
                self._logger.error(f"Failed to write artifact {filename}: {e}")

        items[0].metadata["_executions"] = {
            "artifacts": written,
            "total": len(written),
            "output_dir": str(day_dir),
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

        self._logger.info(
            f"Execution engine: {len(written)} artifacts written to {day_dir}",
            extra={"artifacts": len(written)},
        )
        return items

    # ─── Decision-type executors ─────────────────────────────────────────

    def _execute_decision(self, decision: dict) -> dict | None:
        dtype = decision.get("type")
        if dtype == "build_feature":
            return self._exec_build_feature(decision)
        elif dtype == "launch_campaign":
            return self._exec_launch_campaign(decision)
        elif dtype == "write_content":
            return self._exec_write_content(decision)
        elif dtype == "reach_out":
            return self._exec_reach_out(decision)
        elif dtype == "monitor_competitor":
            return self._exec_monitor_competitor(decision)
        elif dtype == "investigate":
            return self._exec_investigate(decision)
        return None

    def _exec_build_feature(self, decision: dict) -> dict:
        """Generate a GitHub issue markdown for a build_feature decision."""
        target = decision.get("target", "")
        rationale = decision.get("rationale", "")
        action = decision.get("suggested_action", "")
        evidence = decision.get("evidence", [])

        evidence_md = "\n".join(
            f"- [{e.get('title', 'Untitled')}]({e.get('url', '')}) — _{e.get('source', '')}_"
            for e in evidence
        ) or "_No specific items tracked._"

        content = f"""# Build alternative for {target}

> Auto-generated by Market-Intel Decision Engine
> Decision ID: `{decision.get('id', '')}`
> Priority: **{decision.get('priority', 'P2')}**
> Expected impact: **{decision.get('expected_impact', 'medium')}**
> Generated: {decision.get('created_at', '')}

## Summary

{action}

## Rationale

{rationale}

## Acceptance criteria

- [ ] Feature parity with {target} for the top 3 pain points documented below
- [ ] Pricing at least 30% below {target}'s entry tier
- [ ] Migration guide / one-click import from {target}
- [ ] Onboarding flow under 5 minutes for first value
- [ ] Public comparison page addressing each documented pain point

## Evidence (market signals backing this decision)

{evidence_md}

## Success metrics

- Capture ≥ 5% of users searching "{target} alternative" within 90 days
- ≥ 10 signups/month attributable to comparison content
- Net Promoter Score ≥ 40 among migrated users

## Tracking

- UTM: `?utm_source=market-intel&utm_medium=issue&utm_campaign={target}-alternative`
- Tag issues/PRs with: `market-intel`, `{target}-alternative`
"""
        return {
            "decision_id": decision.get("id", ""),
            "type": "build_feature",
            "format": "github_issue",
            "title": f"Build alternative for {target}",
            "content": content,
        }

    def _exec_launch_campaign(self, decision: dict) -> dict:
        """Generate campaign brief + ad copy variants."""
        target = decision.get("target", "")
        rationale = decision.get("rationale", "")
        action = decision.get("suggested_action", "")
        evidence = decision.get("evidence", [])

        evidence_md = "\n".join(
            f"- [{e.get('title', '')}]({e.get('url', '')})"
            for e in evidence
        ) or "_No specific evidence tracked._"

        content = f"""# Campaign Brief: {target} Alternative

> Decision ID: `{decision.get('id', '')}`
> Priority: **{decision.get('priority', 'P1')}**
> Generated: {decision.get('created_at', '')}

## Objective

{action}

## Targeting

- **Search intent**: "{target} alternative", "cheaper than {target}", "{target} pricing"
- **Audience**: dissatisfied {target} users, marketing ops teams, founders evaluating tools
- **Channels**: Google Search Ads, LinkedIn, comparison content, Reddit threads

## Pain points to address

{rationale}

## Ad copy variants (A/B/C test)

### Variant A — Pain-point forward
**Headline**: Tired of {target}'s pricing?
**Description**: {len(evidence)}+ users complained this month. See the alternative built for teams like yours.
**CTA**: See comparison

### Variant B — Outcome forward
**Headline**: Same power as {target}. Half the cost.
**Description**: Built for marketers who refuse to overpay. Free 14-day trial. No credit card.
**CTA**: Start free trial

### Variant C — Social proof forward
**Headline**: Why teams are switching from {target}
**Description**: Real reviews from {len(evidence)} users who migrated. Read the case studies.
**CTA**: Read case studies

## Landing page requirements

- Side-by-side feature comparison table
- Pricing calculator (input: team size → output: monthly cost vs {target})
- Migration guide / one-click import CTA
- Testimonials carousel (rotate 3 dissatisfied-user quotes)
- Exit intent: free migration concierge offer

## Budget recommendation

- Start: $50/day Google Search, $30/day LinkedIn
- Reallocate to winning variant after 7 days
- Pause if CAC > $80 after 14 days

## Tracking

- UTM: `?utm_source=market-intel&utm_campaign={target}-alt-2026`
- Conversion events: trial_signup, demo_booked, migration_completed
- Dashboard: weekly cohort comparison A vs B vs C

## Market evidence

{evidence_md}
"""
        return {
            "decision_id": decision.get("id", ""),
            "type": "launch_campaign",
            "format": "campaign_brief",
            "title": f"Campaign Brief: {target} Alternative",
            "content": content,
        }

    def _exec_write_content(self, decision: dict) -> dict:
        """Generate blog post outline + SEO keyword list."""
        target = decision.get("target", "")
        rationale = decision.get("rationale", "")
        action = decision.get("suggested_action", "")
        evidence = decision.get("evidence", [])
        urgency = decision.get("urgency_hours")

        urgency_note = f"\n> ⏰ Publish within {urgency // 24} days to ride the trend wave." if urgency else ""

        evidence_md = "\n".join(
            f"- [{e.get('title', '')}]({e.get('url', '')})"
            for e in evidence
        ) or "_No specific evidence tracked._"

        # Generate SEO keywords from target + variations
        kw_target = target.lower().replace(" ", "-")
        keywords = [
            target,
            f"{target} guide",
            f"{target} tutorial",
            f"{target} best practices",
            f"{target} examples",
            f"{target} tools",
            f"how to {target}",
            f"{target} for beginners",
            f"{target} 2026",
        ]

        content = f"""# Content Brief: {target}

> Decision ID: `{decision.get('id', '')}`
> Priority: **{decision.get('priority', 'P2')}**{urgency_note}
> Generated: {decision.get('created_at', '')}

## Topic & angle

{action}

## Why now

{rationale}

## SEO keywords (primary + secondary)

Primary: `{target}`

Secondary:
{chr(10).join(f'- `{k}`' for k in keywords[1:])}

## Outline (target 1500-2000 words)

1. **Hook** (150 words)
   - Open with the concrete pain point users are voicing (cite evidence)
   - Promise: by end of post, reader will know how to solve it
2. **What is {target}?** (200 words)
   - Define in plain English
   - Why it matters in 2026
3. **Why {target} is trending right now** (300 words)
   - Cite the {len(evidence)} market signals we detected
   - Include data: mention count, growth rate, who's talking about it
4. **The 3 biggest pain points with {target}** (400 words)
   - Each pain point = one sub-heading
   - Real quotes from the market (anonymized if needed)
5. **How to solve each pain point** (400 words)
   - Practical, step-by-step
   - Include 1 tool recommendation per pain point
6. **Comparison table** (200 words)
   - 5 alternatives side-by-side
   - Pricing, key feature, best for
7. **Conclusion + CTA** (150 words)
   - Recap the trend
   - CTA: download the full comparison PDF / book a demo / subscribe

## Distribution plan

- Publish on blog + syndicate to Medium / dev.to / LinkedIn article
- Share in 3 relevant subreddits (no spam — engage first)
- Email to subscribers with subject line: "{target}: what {len(evidence)} users are saying"
- Repurpose outline into Twitter/X thread (10 tweets)

## Tracking

- UTM: `?utm_source=market-intel&utm_medium=blog&utm_campaign={kw_target}`
- KPIs: organic traffic (30-day), avg time on page, email signups attributed

## Source evidence

{evidence_md}
"""
        return {
            "decision_id": decision.get("id", ""),
            "type": "write_content",
            "format": "content_brief",
            "title": f"Content Brief: {target}",
            "content": content,
        }

    def _exec_reach_out(self, decision: dict) -> dict:
        """Generate personalized cold email drafts."""
        target = decision.get("target", "")
        rationale = decision.get("rationale", "")
        action = decision.get("suggested_action", "")
        evidence = decision.get("evidence", [])

        evidence_md = "\n".join(
            f"- {e.get('title', '')} ({e.get('source', '')})"
            for e in evidence
        ) or "_No specific evidence tracked._"

        content = f"""# Outreach Plan: {target}

> Decision ID: `{decision.get('id', '')}`
> Priority: **{decision.get('priority', 'P1')}**
> Generated: {decision.get('created_at', '')}

## Goal

{action}

## Email template A — Soft touch (high conversion)

**Subject**: Saw your question about {target} — quick thought

Hi [First name],

I noticed you were asking about {target} in [source/community]. We just shipped [feature] specifically because {len(evidence)}+ people flagged the same pain point this month.

Worth a 15-min call to compare notes? I can also send a 1-page comparison sheet if you'd rather skim first.

— [Your name]

## Email template B — Direct (faster cycle)

**Subject**: {target} alternative — built for teams like yours

Hi [First name],

Quick context: we built [product] because {target}'s pricing didn't make sense for teams under 50 people. {len(evidence)} users this month alone mentioned the same thing.

Free 14-day trial, no credit card: [link]

Worth trying?

— [Your name]

## Email template C — Value-first (slower but stickier)

**Subject**: Comparison sheet: {target} vs 5 alternatives

Hi [First name],

I put together a side-by-side comparison of {target} and 5 alternatives, including pricing, feature gaps, and migration effort. Free download, no email wall: [link]

If it's useful, happy to walk you through it on a call.

— [Your name]

## Outreach sequence (5 touches over 14 days)

1. Day 0: Email A (soft touch)
2. Day 2: LinkedIn connect (no pitch)
3. Day 4: Email B (direct) — only if no reply
4. Day 7: Share comparison sheet (Email C)
5. Day 14: Breakup email: "Assuming timing's off — closing the loop"

## Personalization variables

For each prospect, fill in:
- [First name]
- [source/community] — pull from evidence below
- [feature] — the most relevant feature to their stated pain
- [product] — your product name

## Market evidence (use for personalization)

{evidence_md}

## Tracking

- Log each send in CRM
- UTM on all links: `?utm_source=outreach&utm_campaign={target}-conversion`
- Reply rate target: ≥ 8% (cold email benchmark)
"""
        return {
            "decision_id": decision.get("id", ""),
            "type": "reach_out",
            "format": "email_sequence",
            "title": f"Outreach Plan: {target}",
            "content": content,
        }

    def _exec_monitor_competitor(self, decision: dict) -> dict:
        """Generate a watchlist entry."""
        target = decision.get("target", "")
        rationale = decision.get("rationale", "")
        action = decision.get("suggested_action", "")

        content = f"""# Competitor Watchlist: {target}

> Decision ID: `{decision.get('id', '')}`
> Priority: **{decision.get('priority', 'P2')}**
> Generated: {decision.get('created_at', '')}

## Watch trigger

{rationale}

## Action

{action}

## Weekly checklist

- [ ] Check {target} blog / changelog for new releases
- [ ] Check {target} pricing page for changes
- [ ] Check LinkedIn for new hires (esp. sales / product leadership)
- [ ] Check Crunchbase for funding announcements
- [ ] Check Twitter / Reddit for new feature launches or user complaints
- [ ] Note any {target} customer migrations TO or FROM our product

## Signals to escalate immediately

- Price drop > 20% → P0 defensive campaign
- New enterprise feature launch → assess build vs buy
- Acquisition announcement → reassess competitive position
- Founder / CTO departure → opportunity window opens

## Review cadence

- Weekly: this checklist
- Monthly: written summary of {target}'s moves + our counter-moves
- Quarterly: full competitive teardown refresh
"""
        return {
            "decision_id": decision.get("id", ""),
            "type": "monitor_competitor",
            "format": "watchlist",
            "title": f"Watchlist: {target}",
            "content": content,
        }

    def _exec_investigate(self, decision: dict) -> dict:
        """Generate an investigation ticket."""
        target = decision.get("target", "")
        rationale = decision.get("rationale", "")

        content = f"""# Investigation: {target}

> Decision ID: `{decision.get('id', '')}`
> Priority: **{decision.get('priority', 'P2')}**
> Generated: {decision.get('created_at', '')}

## Why investigate

{rationale}

## Investigation plan

1. Pull 30 days of mentions from market-intel DB
2. Identify pattern: who/what/where/when/why
3. Cross-reference with entity graph
4. Hypothesize driver (product launch? pricing change? outage? viral moment?)
5. Document findings + recommend next action

## Output

- Written brief (1-page max) in `investigations/{target}.md`
- Updated entity graph node for {target} with new attribute `investigated=True`
- If material: trigger new decision in next market-intel run
"""
        return {
            "decision_id": decision.get("id", ""),
            "type": "investigate",
            "format": "investigation_ticket",
            "title": f"Investigation: {target}",
            "content": content,
        }
